version: 2.1
aliases:
  - &only-tagged-releases
    tags:
      only: /^\d+\.\d+\.\d+(-[a-z\d\-.]+)?$/
    branches:
      ignore: /.*/
  - &only-untagged
    tags:
      ignore: /.*/
executors:
  cypress:
    docker:
      - image: cypress/base:12
  node:
    docker:
      - image: circleci/node:12.18
commands:
  cache-restore:
    steps:
      - restore_cache:
          keys:
            - node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v2-{{ .Branch }}-
            - node-v2-
  ensure-installed:
    steps:
      - checkout
      - cache-restore
      - run:
          name: npm ci
          command: npm ci
jobs:
  deploy:
    executor: node
    steps:
      - ensure-installed
      - run:
          name: Gatsby build
          command: npm run build
      - run:
          name: Deploy to S3
          command: npm run deploy
  install-and-cache:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - save_cache:
          key: v1-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ./node_modules
            - /root/.cache
  test:
    executor: node
    steps:
      - ensure-installed
      - run:
          name: Test
          command: npm test
      - run:
          name: Test audit
          command: npm run test:audit
      - run:
          name: Test format
          command: npm run test:format
      - run:
          name: Test license
          command: npm run test:license
      - run:
          name: Test lint
          command: npm run test:lint
      - run:
          name: Test types
          command: npm run test:types
  test-cypress:
    executor: cypress
    steps:
      - ensure-installed
      - run:
          name: Start gatsby
          command: npm run develop
          background: true
      - run:
          name: Wait for gatsby
          command: bash ./bin/gatsby_wait_for_ready.sh
      - run:
          name: Run cypress
          command: npx cypress run
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - install-and-cache
      - test:
          requires:
            - install-and-cache
      - test-cypress:
          requires:
            - install-and-cache
      - deploy:
          name: deploy-release
          requires:
            - test
            - test-cypress
          filters: *only-tagged-releases
      - approve-deploy-commit:
          type: approval
          requires:
            - test
            - test-cypress
          filters: *only-untagged
      - deploy:
          name: deploy-commit
          requires:
            - approve-deploy-commit
          filters: *only-untagged
